services:
  - type: web
    name: level-4-capstone-server
    env: node
    rootDir: .
    buildCommand: npm install && npm run render:build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: 3000
